#!/bin/bash -e

if [ $# -lt 2 ]; then
	echo "out directory and/or destination missing"
	exit 1
fi

OUTDIR=${1}
TARGET=root@${2}
BASEDIR=$(pwd)

ssh ${TARGET} mkdir -p /usr/lib/chromium-browser/libs

scp -r ${BASEDIR}/${OUTDIR}/lib*so ${TARGET}:/usr/lib/chromium-browser
scp -r ${BASEDIR}/${OUTDIR}/lib/*so ${TARGET}:/usr/lib/chromium-browser/libs
scp -r ${BASEDIR}/${OUTDIR}/chrome ${TARGET}:/usr/lib/chromium-browser/chromium-browser
#scp -r ${BASEDIR}/${OUTDIR}/* ${TARGET}:/usr/lib/chromium-browser/

# Quick hack to make different types of builds work
ssh ${TARGET} ln -snf /usr/lib/chromium-browser/libs /usr/lib/chromium-browser/lib
