#!/bin/sh
#
# Copyright (C) 2012 Mario Sanchez Prada.
# Authors: Mario Sanchez Prada <mario@mariospr.org>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 (or later)
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# This script updates your WebKit local respository in a faster way
# than just using git-svn rebase by fetching changes from the git
# mirror to the associated remote repository first, then updating the
# references in your local branch tracking the SVN repository.

# Localnet provider
dbus-send --print-reply --type=method_call \
--dest='org.freedesktop.Geoclue.Providers.Localnet' \
/org/freedesktop/Geoclue/Providers/Localnet \
org.freedesktop.Geoclue.Localnet.SetAddressFields \
"string:''" "string:'Finland'" "string:''" "string:'Helsinki'" "string: ''" "string: ''" "string:'Solnantie 24'"

# Manual provider
dbus-send --print-reply --type=method_call \
--dest='org.freedesktop.Geoclue.Providers.Manual' \
/org/freedesktop/Geoclue/Providers/Manual \
org.freedesktop.Geoclue.Manual.SetAddressFields \
"int32:86400" "string:''" "string:'Finland'" "string:''" "string:'Helsinki'" "string: ''" "string: ''" "string:'Solnantie 24'"

# Open the test ui to confirm
geoclue-test-gui
